name: Preview Home Page

on:
  workflow_dispatch:
  pull_request_target:
    paths:
      - "projects/fastgpt/**"
    branches:
      - "new-home"
      - "main"

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    permissions:
        actions: read # Only required for private GitHub Repo
        contents: read
        deployments: write
        pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        env:
          NEXT_PUBLIC_HOME_URL: https://tryfastgpt.ai
          NEXT_PUBLIC_USER_URL: https://cloud.tryfastgpt.ai
        run: |
          cd projects/fastgpt
          npm install
          npm run build
      - name: Deploy to Cloudflare Pages
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./projects/fastgpt/out --project-name=fastgpt-home-run
      - name: print deployment-url
        env:
          DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
        run: echo $DEPLOYMENT_URL